### ISSUE TITLE
How to stop the script before switching to the app version?

### ISSUE THREAD

**Issue by AlexanderProd** [kush-agra/Dynamic_Walls#11]
How can I stop the script before switching to the app version or just updating it?

**Comment by kush-agra** [comment]
If you are using a cron job to run it then just go to terminal and write ```env EDITOR=nano crontab -e``` and erase the line and then control + o and then enter and control + x to save it

If you are using a version above 1.7.4 then run the command `launchctl list | grep -v com.apple` and find the activity with label `wallpaper` or `Dynamic_Walls.Scheduler`

next just run the command `launchctl unload -w /Users/<YOUR USERNAME>/Library/LaunchAgents/<NAME OF THE LABEL YOU SAW ABOVE>.plist`

Let me know if that works :)

**Comment by AlexanderProd** [comment]
the `launchctl list | grep -v com.apple` command told me that there's a activity called wallpaper running. 
But running `launchctl unload -w /Users/<YOUR USERNAME>/Library/LaunchAgents/wallpaper.plist` returned _No such file or directory_.

Then I took a look at the `/Users/<YOUR USERNAME>/Library/LaunchAgents/` folder and found the _Dynamic_walls.Scheduler.plist_ file. 
 
After that I ran the `launchctl unload -w /Users/<YOUR USERNAME>/Library/LaunchAgents/Dynamic_walls.Scheduler.plist` command and it successfully stopped the process. 

I hope this was the right approach.
