### ISSUE TITLE
Can't delete script.

### ISSUE THREAD

**Issue by cosmmmic** [kush-agra/Dynamic_Walls#12]
I've deleted all the files. But now Terminal keeps telling me that I have unread mail which contains errors about missing or whatever like that. How to completely disable it? I've used alpha version which was installed with terminal in 3rd step. Help me

**Comment by kush-agra** [comment]
Oh the cron job? type this in terminal `env EDITOR=nano crontab -e` remove the first line and control + o then enter and control + x

then in terminal type mail, enter and then type`del *`
