### ISSUE TITLE
I Have no idea what I'm doing and wondering if this will mess up my Mac

### ISSUE THREAD

**Issue by saleh6200** [kush-agra/Dynamic_Walls#13]
So I probably should not have been messing with things like this yet as I am pretty basic in my coding knowledge. I have deleted everything related to this, but my theme seems to be stuck on dark mode even after changing the command to false in the script. 

How do I get this off, or kill it all in terminal? And also when the actual Mojave update comes out, will this mess that up? 

Need help

**Comment by kush-agra** [comment]
Oh don't worry it's nothing, open system preferences on your mac and then general and untick the use dark menu bar and dock option

**Comment by saleh6200** [comment]
Thanks so much man, I feel stupid for that one haha
