### ISSUE TITLE
Minor JSON issue - doesn't affect performance

### ISSUE THREAD

**Issue by kush-agra** [kush-agra/Dynamic_Walls#8]
There seems to some issue where the shell script would sometimes return a "No JSON object could be decoded" error, usually at the 59th minute

although it doesn't affect the script negatively in anyway as it starts working again the next minute, what seems to be causing that, my guess is it's the API crapping out?

**Comment by john2691** [comment]
I saw the error a few times myself, it turned out to be a network issue. Is it possible that you're sending too many requests in a given time frame?

**Comment by kush-agra** [comment]
well it's not set to send a request at the 59th minute, it's just something I noticed while manually running it, but it does do it sometimes at other times too

That is what I though too, maybe I'm sending too many requests but I checked the API documentation and it says nothing about it, but not really an issue as it doesn't affect anything
