### ISSUE TITLE
LaunchAgent command mistakes

### ISSUE THREAD

**Issue by Dniel97** [kush-agra/Dynamic_Walls#9]
I tried the new launchd generator, but there were some mistakes:
Line 14 instead of:
`<string>/Users/var/Pictures/Wallpapers/Dynamic_Walls.scpt</string>` it should be: `<string>/Users/$var/Pictures/Wallpapers/Dynamic_Walls.scpt</string>`
Line 23 instead of: `</plist>" > /Users/$var/Library/LaunchAgents/Dynamic_walls.Scheduler.plist` it should be: `</plist>" > /Users/$var/Library/LaunchAgents/wallpaper.plist`

EDIT: Example: 
[wallpaper_plistGenerator.zip](https://github.com/kush-agra/Dynamic_Walls/files/2098126/wallpaper_plistGenerator.zip)

**Comment by kush-agra** [comment]
line 23 the plist name can be custom, it's not restricted to just wallpaper?

and I did notice the first issue and it still worked for me idk how so I let it be, I'll fix it though

**Comment by Dniel97** [comment]
Of course you can name it, as you like, but when you rename the plist, you should also rename the plist in line 27 to load properly.

**Comment by kush-agra** [comment]
Ah I pushed the wrong version thinking it was working, of course it was working as i had the correct plist loaded already
